server:
  port: 9001
  
spring:
  application:
    name: user-service
  config:
      activate:
         on-profile: default
  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
      jdbc.batch_size: 10
      ejb:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      
  datasource:
    url: jdbc:mysql://localhost:3306/bitofops_user_db?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: taha@123
     

app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10
  cors:
    allowed-origins: http://localhost:9007
 

logging:
  level:
    org.springframework.security: DEBUG


spring.batch.initialize-schema: never

#spring.batch.initialize-schema: NEVER
spring.batch.jdbc.initialize-schema : ALWAYS

spring.batch.job.enabled: false

rest.api.url: https://extranet.ffkmda.fr/api/v1/structures


logging.level.org.hibernate.SQL: DEBUG
logging.level.org.springframework.cache: TRACE