name: Build and Push user management Docker Image
'on':
  push:
    branches:
      - main
env:
  username: '${{ secrets.DOCKER_USERNAME }}'
  password: '${{ secrets.DOCKER_PASSWORD }}'
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    
    - name: Build shared Library with maven
      run: mvn clean install --file server/shared/pom.xml -DskipTests
  
    - name: Build with maven
      run: mvn -B package verify --file server/services/user-service/pom.xml -DskipTests
      working-directory: server/services/user-service
    
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: tahanebti/bitsoftnops-user-service
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
