name: Build and Push user management Docker Image
'on':
  push:
    branches:
      - main
env:
  username: '${{ secrets.DOCKER_USERNAME }}'
  password: '${{ secrets.DOCKER_PASSWORD }}'
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
- uses: actions/checkout@v2
    - run: mv -f server/* . 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - run: mvn dependency:go-offline -B    
    - run: mvn -B package --file pom.xml -DskipTests
    - run: mkdir staging && cp server/services/user-service/target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
          name: Package
          path: staging

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: tahanebti/bitsoftnops-user-service
        tags: latest
        registry: docker.io
        dockerfile: server/services/user-service/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
