name: Build and Push user management Docker Image
'on':
  push:
    branches:
      - main
env:
  username: '${{ secrets.DOCKER_USERNAME }}'
  password: '${{ secrets.DOCKER_PASSWORD }}'
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - run: mvn clean install -f server/shared/logger/pom.xml -DskipTests
    - run: mvn clean install -f server/shared/core/pom.xml -DskipTests
    - run: mvn -B package -f server/services/user-service/pom.xml -DskipTests
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
          name: Package
          path: staging
    
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: tahanebti/bitsoftnops-user-service
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
