name: Build and Push user management Docker Image
'on':
  push:
    branches:
      - main
env:
  username: '${{ secrets.DOCKER_USERNAME }}'
  password: '${{ secrets.DOCKER_PASSWORD }}'
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
  

    - name: Build Docker images
      if: docker-build.sh
      run: |
          ls
          ./docker-build.sh
    
    - name: Push Docker images to Docker registry
      if: docker-build.sh
      uses: docker/login-action@v1
      with:
        registry: docker.io
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Publish Docker images
      if: docker-build.sh
      run: |
        docker push tahanebti/bitsoftnops-user-service:latest
        
