name: Build and Push user management Docker Image
'on':
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
env:
  username: '${{ secrets.DOCKER_USERNAME }}'
  password: '${{ secrets.DOCKER_PASSWORD }}'
jobs:
      
 #Build's job
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./server/services/user-service
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      - run: mv -f server/* . 
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven
    
      - run: mvn clean install --file pom.xml -DskipTests
    
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: tahanebti/bitsoftnops-user-service
          tags: latest
          registry: docker.io
          dockerfile: services/user-service/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
