name: Build and Push Docker Image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: |
            mv -f server/shared/logger/* .
            mv -f server/shared/core/* .
            mv -f server/services/user-service/* . 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - run: mvn dependency:go-offline -B    
    - run: mvn -B package -f server/shared/logger --file pom.xml -DskipTests
    - run: mvn -B package -f server/shared/core --file pom.xml -DskipTests
    - run: mvn -B package f server/services/user-service --file pom.xml -DskipTests
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
          name: Package
          path: staging

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: tahanebti/bitofops/user-service
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}





